### ISSUE TITLE
Typo in openapi.yaml

### ISSUE THREAD

**Issue by lucamartellucci78** [open-mpic/open-mpic-specification#1]
Hi,
if you search for "validaiton-details" into openapi.yaml file, you're going to find a couple of matches!
I think it should be validation-details instead.
Thanks for the great work!
Luca

**Comment by gcimaszewski** [comment]
Thanks for spotting this, it has been fixed in [this commit](https://github.com/open-mpic/open-mpic-specification/commit/bd5206865d3c83d7f8cf91eea90cfac5ff94ed75).
