### ISSUE TITLE
Mistmatch between API spec and API example

### ISSUE THREAD

**Issue by lucamartellucci78** [open-mpic/open-mpic-specification#2]
Hi,
into the openapi.yaml file, the HTTPValidation schema has a property called "expected-challenges" but the examples  have a different property: "expected-value"!
Thanks
Luca

**Comment by birgelee** [comment]
Hi Luca,

Thanks for catching this. The original prototype and the spec were developed concurrently, and the prototype was then conformed to the spec (potentially causing some naming changes to be missed).

We are currently considering a major refactor by Dmitry Sharkov (see [PR #3](https://github.com/open-mpic/aws-lambda-python/pull/3)). To avoid merge conflicts I may wait to merge in this pull before fixing this issue, but this will be addressed shortly.

**Comment by birgelee** [comment]
Given the codebase currently uses expected-challenge and expected-challenge was used in the main part of the schema, I updated all references in the spec to use expected-challenge.
